language: python
python:
  - 2.6
  - 2.7
install:
    - pip install -r etc/requirements.txt
before_script:
    - cp local_settings_template.py local_settings.py
    - python manage.py syncdb --noinput
    - python manage.py migrate
script:
    - python manage.py test